### ISSUE TITLE
Vagrant or Docker

### ISSUE THREAD

**Issue by jnordling** [qlands/FormShare#1]
I have been using and building with the Onadata stack for sometime now, happy to see a continuation. The biggest thing about this app is that the API is kind of in a strange state, the API and the UI are two tightly coupled. Im down to work on it.

One thing that would really increase this applications value is a local build with vagrant or Docker. 

Ill be taking a look at the modification you made to see best place to hope in.

Best,
Jon

**Comment by qlands** [comment]
Hi,
Great to see a first issue here in less than 24 hours!

Right now I am continuing polishing the current code before I start fixing some of the bugs and embarking into new things. We need to see the API from a different less since FormShare is not intended as a Software as Service but for organizations to manage their ODK surveys. So maybe bits of the API might not be necessary. My focus in the coming week will be on fixing the data views (lots of bugs there) and photos.

Let me have a look at Vagrant or Docker.  Please feel free to contribute.

Thanks.

**Comment by qlands** [comment]
Hi Jon,

I created a Docker for testing that you can get it here:

> docker pull qlands/formshare

As it is for initial testing it is based on the master branch. It starts FormShare in a Apache server in /formshare. Because of #2 you will not see the images. Once I have #2 ready I will push things to stable 1.1.0
